theodorusclarence/ts-nextjs-tailwind-starter

CHANGELOG.md, src/components/buttons/Button.tsx, src/components/links/ArrowLink.tsx, src/components/links/ButtonLink.tsx, src/components/links/CustomLink.tsx, src/components/links/UnstyledLink.tsx, src/pages/404.tsx, src/pages/components.tsx, src/pages/index.tsx, src/styles/globals.css
- feat: add new button variants
- feat: change CustomLink default ring
- feat: split next/link props type
- feat: change default theme to light
- Resolve #50
=> i50 remove animated underline from buttons

CHANGELOG.md, README.md
=> chore: add 0.2.0 changelog

next-env.d.ts, package.json, src/pages/components.tsx, src/styles/colors.css, tailwind.config.js, yarn.lock
- chore(package): update to tailwindcss 3.0.1
- feat: update tailwindcss color names
- Resolve #59
=> i59 upgrade to tailwind v3

src/pages/_app.tsx
=> feat: add Layout component to _app

CHANGELOG.md, src/components/NextImage.tsx, src/components/buttons/Button.tsx, src/components/links/ButtonLink.tsx
- feat: center Button & ButtonLink vertically
- fix: can't use layout fill on NextImage
- chore: release 0.5.0
=> button uncentered

.eslintrc.js, .github/workflows/lint.yml, .vscode/typescriptreact.code-snippets, CHANGELOG.md, package.json, src/components/buttons/Button.tsx, src/components/links/ArrowLink.tsx, src/components/links/ButtonLink.tsx, src/components/links/PrimaryLink.tsx, src/components/links/UnderlineLink.tsx, src/pages/components.tsx, src/pages/index.tsx, yarn.lock
- chore(eslint): add unused import autofix
- feat: add PrimaryLink and rename UnderlineLink
- feat: change primary variant to darker shade
- chore: change typecheck script
- chore: add generic to useState snippet
- Resolve #70
=> i70 add primary link & remove unused import eslint

.prettierrc.js
=> chore: add clsxm config to class sorter

.eslintrc.js, src/components/buttons/Button.tsx, src/components/links/ButtonLink.tsx, src/components/links/PrimaryLink.tsx, src/components/links/UnderlineLink.tsx, src/components/links/UnstyledLink.tsx
- feat: add forward ref to Button
- refactor: change button class order for clsxm
- Resolve #78
=> i78 buttons

next.config.js, package.json, public/svg/Vercel.svg, src/pages/index.tsx, tsconfig.json, yarn.lock
- chore: add absolute public import
- feat: add support for svgr
- Resolve #80
=> i80 add support for svgr

src/pages/_app.tsx
=> fix: layout declared twice

CHANGELOG.md, src/components/NextImage.tsx, src/components/Skeleton.tsx, src/pages/components.tsx, tailwind.config.js
- feat: add Skeleton component
- feat: change NextImage loader to shimmer
https://user-images.githubusercontent.com/55318172/155867729-8c3176ad-ede4-4443-b42b-780517615e5a.mp4
- Resolve #112
- Resolve #97
=> i112 implement shimmer

src/components/NextImage.tsx, src/pages/components.tsx
reverting for new because NextImage with shimmer loads every page changes (doesn't looking good)
=> revert: change NextImage loader to shimmer

package.json, tailwind.config.js, yarn.lock
- chore: upgrade tailwindcss to 3.1
- feat: use 1st party tailwindconfig types
- feat: use new css variable tailwind colors config
=> upgrade tw

.github/workflows/release-please.yml, CHANGELOG.md, README.md, package.json, yarn.lock
=> feat: add release-please

.github/workflows/release-please.yml
because no event specified, changing to full commented code
=> fix: release please trigger workflow error

.gitignore, next.config.js, package.json, src/components/NextImage.tsx, src/components/links/UnstyledLink.tsx, yarn.lock
=> chore: upgrade to next 13

next.config.js, src/components/buttons/Button.tsx, src/components/buttons/IconButton.tsx, src/components/buttons/TextButton.tsx, src/components/links/IconLink.tsx, src/components/links/PrimaryLink.tsx, src/pages/_document.tsx, src/pages/components.tsx
- feat: update _document to new format
- feat: add button & link components with new style
=> update next13 document and new components

.github/workflows/issue-autolink.yml
bumping to 1.8.1 and add permission
Provide screenshots or videos of the changes made if any.
=> fix: issue autolink not working

.github/workflows/issue-autolink.yml, src/pages/index.tsx
- ci: change autolink to body style
- fix: footer overlaps with content
=> update index and issue

src/pages/components.tsx
see here image not found
https://tsnext-tw.thcl.dev/components
=> fix: image in components page

package.json, src/components/buttons/Button.tsx, src/components/buttons/IconButton.tsx, src/components/buttons/TextButton.tsx, src/components/links/ButtonLink.tsx, src/components/links/IconLink.tsx, src/components/links/PrimaryLink.tsx, src/components/links/UnderlineLink.tsx, src/pages/components.tsx, src/styles/colors.css, tailwind.config.ts, yarn.lock
Upgrade Tailwind CSS v3
Provide screenshots or videos of the changes made if any.
=> feat: upgrade to tailwindcss v3.3

package.json, yarn.lock
Describe problems, if any, clearly and concisely.
Summarize the impact to the system.
Please also include relevant motivation and context.
Please include a summary of the technical solution and how it solves the problem.
Provide screenshots or videos of the changes made if any.
=> feat: upgrade to next v13.3

README.md
- The MUI version that uses this starter
=> docs: add MUI version that using this starter

package.json, pnpm-lock.yaml, src/app/page.tsx, src/lib/env.ts
add env type checker. process.env is now type safe
=> feat: add env type checker

src/styles/globals.css
Fixes #236 
Provide screenshots or videos of the changes made if any.
=> feat: set font block to default

.github/workflows/lint.yml
=> chore: upgrade lint packages to support pnpm 9

renovate.json
remove renovate since we're using depfu
=> ci: remove renovate
